name: my_portfolio
description: "My developer portfolio app built with Flutter. Showcasing my projects, skills, and contact information in a sleek and responsive design."

publish_to: 'none'

version: 1.1.2+1

environment:
  sdk: ^3.10.8

dependencies:
  cupertino_icons: ^1.0.8
  firebase_analytics: ^12.1.2
  firebase_core: ^4.4.0
  firebase_remote_config: ^6.1.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  font_awesome_flutter: ^10.12.0
  google_fonts: ^8.0.2
  logger: ^2.6.2
  melos: ^7.4.0
  path: ^1.9.1
  remote_config:
    path: packages/remote_config
  slang: ^4.12.1
  slang_flutter: ^4.12.1
  url_launcher: ^6.3.2
  very_good_analysis: ^10.2.0
  web: ^1.1.1
  yaml_edit: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

melos:
  scripts:
    slang:
      run: dart run slang

    generate_assets_folders:
      run: dart run my_portfolio:assets_linux

    run_release_deploy:
      run: >
        flutter build web --release &&
        cd build/web &&
        rm -rf .git &&
        git init &&
        git add . &&
        git commit -m "Update" &&
        git branch -M gh-pages &&
        git remote add origin https://github.com/guilhermeeng99/guilhermeeng99.github.io.git &&
        git push -f origin gh-pages

flutter:

  assets:
    - lib/app/assets/i18n/
    - lib/app/assets/images/
    - lib/app/assets/images/projects/
  uses-material-design: true
