name: remote_config

publish_to: "none"

environment:
  sdk: ">=3.1.4 <4.0.0"
  flutter: ">=3.22.1"

dependencies:
  flutter:
    sdk: flutter
  firebase_remote_config: ^6.1.4

dev_dependencies:
  flutter_lints: 4.0.0
